version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: ./pm25
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./pm25:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    sysctls:
      - net.core.somaxconn=4096
    ports:
      - "6379:6379"
  queue_worker:
    build:
      context: ./pm25
      dockerfile: Dockerfile.worker
    command: bash -c "chmod +x entrypoint-worker.sh && ./entrypoint-worker.sh"
    volumes:
      - ./pm25:/app
    depends_on:
      - web
  queue_scheduler:
    build:
      context: ./pm25
      dockerfile: Dockerfile.worker
    command: bash -c "chmod +x entrypoint-scheduler.sh && ./entrypoint-scheduler.sh"
    depends_on:
      - web
  queue_monitoring:
    image: mher/flower
    command: flower --basic_auth=parn:parn1234 --address=0.0.0.0 --port=5555 --broker=redis://redis:6379
    ports:
      - '5555:5555'
